<?php

/**
 * BaseTopic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $userId
 * @property integer $categoryId
 * @property string $name
 * @property clob $description
 * @property timestamp $createDate
 * @property timestamp $modDate
 * @property Category $Category
 * @property User $User
 * @property Doctrine_Collection $posts
 * @property Doctrine_Collection $topicTags
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id$
 */
abstract class BaseTopic extends Aerial_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('Topic');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('userId', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('categoryId', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => '45',
             ));
        $this->hasColumn('description', 'clob', 65535, array(
             'type' => 'clob',
             'length' => '65535',
             ));
        $this->hasColumn('createDate', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('modDate', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));


        $this->index('fk_Topic_Category1', array(
             'fields' => 
             array(
              0 => 'categoryId',
             ),
             ));
        $this->index('fk_Topic_User1', array(
             'fields' => 
             array(
              0 => 'userId',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'categoryId',
             'foreign' => 'id',
             'onDelete' => 'set null',
             'onUpdate' => 'set null'));

        $this->hasOne('User', array(
             'local' => 'userId',
             'foreign' => 'id'));

        $this->hasMany('Post as posts', array(
             'local' => 'id',
             'foreign' => 'topicId'));

        $this->hasMany('TopicTag as topicTags', array(
             'local' => 'id',
             'foreign' => 'topicId'));
    }
    public function construct()
    {
        $this->mapValue('_explicitType', 'org.aerial.vo.Topic');
    }
}