<?php

/**
 * BaseTopicTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $topicId
 * @property integer $tagId
 * @property Topic $Topic
 * @property Tag $Tag
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id$
 */
abstract class BaseTopicTag extends Aerial_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('TopicTag');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('topicId', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('tagId', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));


        $this->index('fk_TopicTag_Topic1', array(
             'fields' => 
             array(
              0 => 'topicId',
             ),
             ));
        $this->index('fk_TopicTag_Tag1', array(
             'fields' => 
             array(
              0 => 'tagId',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Topic', array(
             'local' => 'topicId',
             'foreign' => 'id'));

        $this->hasOne('Tag', array(
             'local' => 'tagId',
             'foreign' => 'id'));
    }
    public function construct()
    {
        $this->mapValue('_explicitType', 'org.aerial.vo.TopicTag');
    }
}