<?php

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $username
 * @property string $password
 * @property timestamp $createDate
 * @property timestamp $modDate
 * @property Doctrine_Collection $posts
 * @property Doctrine_Collection $comments
 * @property Doctrine_Collection $categories
 * @property Doctrine_Collection $topics
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id$
 */
abstract class BaseUser extends Aerial_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('User');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('username', 'string', 45, array(
             'type' => 'string',
             'unique' => true,
             'length' => '45',
             ));
        $this->hasColumn('password', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('createDate', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('modDate', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Post as posts', array(
             'local' => 'id',
             'foreign' => 'userId'));

        $this->hasMany('Comment as comments', array(
             'local' => 'id',
             'foreign' => 'userId'));

        $this->hasMany('Category as categories', array(
             'local' => 'id',
             'foreign' => 'userId'));

        $this->hasMany('Topic as topics', array(
             'local' => 'id',
             'foreign' => 'userId'));
    }
}