<?php

/**
 * BaseGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $GroupUsers
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id$
 */
abstract class BaseGroup extends Aerial_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('group_table');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('User as Users', array(
             'refClass' => 'GroupUser',
             'local' => 'group_id',
             'foreign' => 'user_id'));

        $this->hasMany('GroupUser as GroupUsers', array(
             'local' => 'id',
             'foreign' => 'group_id'));
    }
    public function construct()
    {
        $this->mapValue('_explicitType', 'org.aerial.vo.Group');
    }
}