<?php

/**
 * BaseTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $topicTags
 * @property Doctrine_Collection $postTags
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id$
 */
abstract class BaseTag extends Aerial_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('Tag');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TopicTag as topicTags', array(
             'local' => 'id',
             'foreign' => 'tagId'));

        $this->hasMany('PostTag as postTags', array(
             'local' => 'id',
             'foreign' => 'tagId'));
    }
    public function construct()
    {
        $this->mapValue('_explicitType', 'org.aerial.vo.Tag');
    }
}